config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :participants
  resources :coordinators
  resources :registries
  resources :enrollment_to_registries
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :emailaddress, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
	validates :phonenumber, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format. Try 123-456-7890" }
	has_many :registry
	has_many :participant
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: [:show, :edit, :update, :destroy]

  # GET /coordinators
  # GET /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1
  # GET /coordinators/1.json
  def show
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators
  # POST /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1
  # PATCH/PUT /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: 'Coordinator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinator_params
      params.require(:coordinator).permit(:name, :emailaddress, :phonenumber)
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_form.html.erb
<%= simple_form_for(@coordinator) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.input :name %>
      <%= f.input :emailaddress %>
      <%= f.input :phonenumber %>
      <%= f.button :submit, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Show', @coordinator %> |
<%= link_to 'Back', coordinators_path %>

app/views/coordinators/index.html.erb
  <h1 class="title">Coordinators</h1>
  
  <hr>

   <h3 class="field">
      <%= link_to new_coordinator_path do%>
      <span class="icon is-small has-text-link">New Coordinator <i class="fa fa-plus"></i></span>
      <% end %>
  </h3>

  <% @coordinators.each do |coordinator| %>
    <div class="card" style="margin-bottom: 5rem;">
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to coordinator do%>
            <%= coordinator.emailaddress %>
          <% end %>    
        </h4>
        <%= link_to 'Edit', edit_coordinator_path(coordinator) %>
        <%= link_to 'Destroy', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
    <% end %>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

app/views/coordinators/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @coordinator.name %>
</p>

<p>
  <strong>Emailaddress:</strong>
  <%= @coordinator.emailaddress %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @coordinator.phonenumber %>
</p>