config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :participants
  resources :coordinators
  resources :registries
  resources :enrollment_to_registries
end

app/models/participant.rb
class Participant < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :emailaddress, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
	validates :phonenumber, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format. Try 123-456-7890" }
	has_many :coordinators
	has_many :registries
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)
    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :gender, :dob, :dateofenrollment, :emailaddress, :phonenumber, :remarks, :coordinator)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :dob, :label => "Date of birth" %>
    <%= f.input :dateofenrollment, :label => "Date of Enrollment" %>
    <%= f.input :emailaddress, :label => "Email Address" %>
    <%= f.input :phonenumber, :label => "Phone Number" %>
    <%= f.input :remarks %>
    <label> Select one coordinator </label>
    <%= collection_select(:participant, :coordinator, Coordinator.all, :emailaddress, :emailaddress, prompt: true)%>
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
  <h1 class="title">Participants</h1>
  
  <hr>

   <h3 class="field">
      <%= link_to new_participant_path do%>
      <span class="icon is-small has-text-link">New Participant <i class="fa fa-plus"></i></span>
      <% end %>
  </h3>

  <% @participants.each do |participant| %>
    <div class="card" style="margin-bottom: 5rem;">
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to participant do%>
            <%= participant.name %>
          <% end %> 
          <h5 class="text-muted"><%= participant.gender %></h5>
          <h5 class="text-muted"><%= participant.dob %></h5>
        </h4>
        <%= link_to 'Edit', edit_participant_path(participant) %>
        <%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
    <% end %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @participant.gender %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @participant.dob %>
</p>

<p>
  <strong>Date of enrollment:</strong>
  <%= @participant.dateofenrollment %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @participant.emailaddress %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @participant.phonenumber %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @participant.remarks %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @participant.coordinator %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |