config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :participants
  resources :coordinators
  resources :registries
  resources :enrollment_to_registries
end

app/models/registry.rb
class Registry < ApplicationRecord
	validates_presence_of :name
	validates_presence_of :location
	validates_presence_of :isactive
	has_many :coordinators
	has_many :participants, :through => :coordinators
	validates :name, uniqueness: { scope: :location }
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: [:show, :edit, :update, :destroy]

  # GET /registries
  # GET /registries.json
  def index
    @registries = Registry.paginate(page: params[:page])
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registry_params
      params.require(:registry).permit(:name, :location, :isactive)
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= simple_form_for(@registry) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :isactive, :label => "Check to open registry" %>

      <%= f.button :submit, :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Edit Registry</h1>

<%= render 'form', registry: @registry %>

app/views/registries/index.html.erb
  <h1 class="title">Registries</h1>
  
  <hr>

   <h3 class="field">
      <%= link_to new_registry_path do%>
      <span class="icon is-small has-text-link">New Registry <i class="fa fa-plus"></i></span>
      <% end %>
  </h3>

  <%= will_paginate @registries %>

  <% @registries.each do |registry| %>
    <div class="card" style="margin-bottom: 5rem;">
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to registry do%>
            <%= registry.name %>
          <% end %>    
        </h4>
        <h5 class="text-muted"><%= registry.location %></h5>
        <%= link_to 'Edit', edit_registry_path(registry) %>
        <%= link_to 'Destroy', registry, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
    <% end %>
  <%= will_paginate @registries %>

app/views/registries/new.html.erb
<h1>New Registry</h1>

<%= render 'form', registry: @registry %>

app/views/registries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @registry.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @registry.location %>
</p>


<% if @registry.isactive %>
	<%= link_to 'Add Participants to Registry', new_enrollment_to_registry_path %>
<% else %>
	<p> This registry is inactive </p>
<% end %>