config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :participants
  resources :coordinators
  resources :registries
  resources :enrollment_to_registries
end

app/models/enrollment_to_registry.rb
class EnrollmentToRegistry < ApplicationRecord
  belongs_to :registry
  belongs_to :coordinator
  belongs_to :participant
  validates :registry_id, uniqueness: { scope: :participant_id }
end

app/controllers/enrollment_to_registries_controller.rb
class EnrollmentToRegistriesController < ApplicationController
  before_action :set_enrollment_to_registry, only: [:show, :edit, :update, :destroy]

  # GET /enrollment_to_registries
  # GET /enrollment_to_registries.json
  def index
    @enrollment_to_registries = EnrollmentToRegistry.all
  end

  # GET /enrollment_to_registries/1
  # GET /enrollment_to_registries/1.json
  def show
  end

  # GET /enrollment_to_registries/new
  def new
    @enrollment_to_registry = EnrollmentToRegistry.new
  end

  # GET /enrollment_to_registries/1/edit
  def edit
  end

  # POST /enrollment_to_registries
  # POST /enrollment_to_registries.json
  def create
    @enrollment_to_registry = EnrollmentToRegistry.new(enrollment_to_registry_params)

    respond_to do |format|
      if @enrollment_to_registry.save
        format.html { redirect_to @enrollment_to_registry, notice: 'Enrollment to registry was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment_to_registry }
      else
        format.html { render :new }
        format.json { render json: @enrollment_to_registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollment_to_registries/1
  # PATCH/PUT /enrollment_to_registries/1.json
  def update
    respond_to do |format|
      if @enrollment_to_registry.update(enrollment_to_registry_params)
        format.html { redirect_to @enrollment_to_registry, notice: 'Enrollment to registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment_to_registry }
      else
        format.html { render :edit }
        format.json { render json: @enrollment_to_registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollment_to_registries/1
  # DELETE /enrollment_to_registries/1.json
  def destroy
    @enrollment_to_registry.destroy
    respond_to do |format|
      format.html { redirect_to enrollment_to_registries_url, notice: 'Enrollment to registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment_to_registry
      @enrollment_to_registry = EnrollmentToRegistry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_to_registry_params
      params.fetch(:enrollment_to_registry, {})
    end
end

app/views/enrollment_to_registries/_form.html.erb
<%= simple_form_for(@enrollment_to_registry) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <label> Select one or more participants </label>
     <%= collection_select(:enrollment_to_registry, :participant_id, Participant.all, :id, :name, {}, { :multiple => true} )%>
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/enrollment_to_registries/edit.html.erb
<h1>Editing Enrollment To Registry</h1>

<%= render 'form', enrollment_to_registry: @enrollment_to_registry %>

<%= link_to 'Show', @enrollment_to_registry %> |
<%= link_to 'Back', enrollment_to_registries_path %>

app/views/enrollment_to_registries/index.html.erb
<h1>Enrollment To Registries</h1>

<table class="responsive nowrap table table-hover" id="dttb-enrollment_to_registries" data-sort="true" data-source="<%= url_for(format: :json)%>">
  <thead>
    <tr>
      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
    </tr>
  </thead>

</table>

<br>

<%= link_to 'New Enrollment To Registry', new_enrollment_to_registry_path %>

app/views/enrollment_to_registries/new.html.erb
<h1>New Enrollment To Registry</h1>

<%= render 'form', enrollment_to_registry: @enrollment_to_registry %>

<%= link_to 'Back', enrollment_to_registries_path %>

app/views/enrollment_to_registries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enrollment_to_registry_path(@enrollment_to_registry) %> |
<%= link_to 'Back', enrollment_to_registries_path %>